### ISSUE TITLE
Old version of React.framework is fetched with 'pod install'

### ISSUE THREAD

**Issue by istvansipos** [mopinion/mopinion-sdk-ios#4]
Hello,

We are using the Mopinion framework in our app, but we encountered a problem when tried to use the latest version with the removed UIWebView. Specifically the `pod install` command fetches an older version of the React.framework which still contains references to UIWebView.

We have the following in our podfile:

> pod 'MopinionSDK',  '~> 0.4.4'
> pod 'React', :git => 'git@github.com:mopinion/mopinion-sdk-ios.git'
> pod 'react-native-webview', :git => 'git@github.com:mopinion/mopinion-sdk-ios.git'
> pod 'yoga', :git => 'git@github.com:mopinion/mopinion-sdk-ios.git'
> pod 'DoubleConversion', :git => 'git@github.com:mopinion/mopinion-sdk-ios.git'
> pod 'GLog', :git => 'git@github.com:mopinion/mopinion-sdk-ios.git'
> pod 'Folly', :git => 'git@github.com:mopinion/mopinion-sdk-ios.git'

Pod install downloads the following items:

> Pre-downloading: `DoubleConversion` from `git@github.com:mopinion/mopinion-sdk-ios.git`, commit `03bd89680ea9e1fe3811b2928c213e69f472a4eb`
> Pre-downloading: `Folly` from `git@github.com:mopinion/mopinion-sdk-ios.git`, commit `03bd89680ea9e1fe3811b2928c213e69f472a4eb`
> Pre-downloading: `GLog` from `git@github.com:mopinion/mopinion-sdk-ios.git`, commit `bfd04415c33ad302b2dfd1bb369a955a8f20edbb`
> Pre-downloading: `React` from `git@github.com:mopinion/mopinion-sdk-ios.git`, commit `03bd89680ea9e1fe3811b2928c213e69f472a4eb`
> Pre-downloading: `react-native-webview` from `git@github.com:mopinion/mopinion-sdk-ios.git`, commit `eefc48070db58c95ba512b1cbe3bb80cd560ce1f`
> Pre-downloading: `yoga` from `git@github.com:mopinion/mopinion-sdk-ios.git`, commit `03bd89680ea9e1fe3811b2928c213e69f472a4eb`

Using

`pod 'React', :git => 'git@github.com:mopinion/mopinion-sdk-ios.git', :tag => '0.4.4'`

or 

`pod 'React', :git => 'git@github.com:mopinion/mopinion-sdk-ios.git', : commit => 'eefc48070db58c95ba512b1cbe3bb80cd560ce1f'`

fixes the problem and everything seems to work well, but now I am afraid that maybe the other frameworks also have an outdated version fetched that can cause some unforeseen issues.

Can you take a look please?

Thank you very much in advance!

**Comment by stevenkuipers** [comment]
Hi,

Thanks for bringing this to our attention. Currently, the support libs in the podspec are not versioned, we will update this to make sure we are specifying the latest versions for the support libs that we are using.
We will update this issue when we have done so.

**Comment by stevenkuipers** [comment]
All support libraries are now versioned in the podspec so any new install should now fetch all the latest versions.

I will now close this issue, if you are still experiencing installation issue you can reply in this thread and we will get back to you
